feat: add modified_time meta tag
jekyll/jekyll-seo-tag pull request #505
Opened 2024-04-11 11:24 UTC by dimaslanjaka

add modified date meta tag, useful for SEO

2025-05-01 16:45 UTC, CookiePLMonster requested changes
This plugin, as well as `jekyll-feed`, make use of `page.last_modified_at`. It would make more sense to use this instead of `page.updated`. This way the SEO tag would match what `jekyll-feed` outputs:
https://github.com/jekyll/jekyll-feed/blob/43cc5d51e30b59ab8d8ba970e42c8c437e2b233f/lib/jekyll-feed/feed.xml#L78

@ashmaroli otherwise this looks good I think? Pinging you directly as per a comment in https://github.com/jekyll/jekyll-seo-tag/issues/512#issuecomment-2611289540 - despite not being the author of this PR, I wish to signal there is interest in this plugin.

2025-05-01 17:53 UTC, ashmaroli commented
I agree with @CookiePLMonster here. It would be better to use the `last_modified_at` attribute here for party between generated feed and SEO markup.

2025-05-01 18:05 UTC, CookiePLMonster commented
Furthermore, even in this plugin, `page.last_modified_at` is already used for LD-JSON generation:
https://github.com/jekyll/jekyll-seo-tag/blob/f449b1af64cbaf9080e7a3c677090cfe6e8f0021/spec/jekyll_seo_tag/drop_spec.rb#L298-L315

Example from my website:
`<script type="application/ld+json">
{"@context":"https://schema.org","@type":"BlogPosting","author":{"@type":"Person","name":"Silent"},"dateModified":"2025-04-23T13:30:00+00:00","datePublished":"2025-04-23T13:30:00+00:00"
```

2025-05-01 21:20 UTC, CookiePLMonster commented
@ashmaroli Looking at https://github.com/jekyll/jekyll-seo-tag/blob/f449b1af64cbaf9080e7a3c677090cfe6e8f0021/lib/jekyll-seo-tag/drop.rb#L114-L123, the current `article:published_time` isn't exactly great either and instead it should be `seo_tag.published_time`. I can prepare an alternative PR tomorrow correcting this + modification date.

2025-05-02 09:10 UTC, CookiePLMonster commented
Additionally, this duplicates #447, albeit using `last_modified_at`.

2026-05-08 17:15 UTC, mattr- commented
Closing in favor of #515 and this feature is now available in 2.9.0

2026-05-08 17:15 UTC, closed without merging